AWSTemplateFormatVersion : '2017-10-18'
Transform: AWS::Serverless-2016-10-31
Description: MXnet-lambda
Resources:
    MXNetFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            CodeUri: .
            Timeout: 300
